//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 06:44:12 PM COT 
//


package org.greypowerservices.webservices.productservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.greypowerservices.webservices.productservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.greypowerservices.webservices.productservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUnitMeasureRequest }
     * 
     */
    public GetUnitMeasureRequest createGetUnitMeasureRequest() {
        return new GetUnitMeasureRequest();
    }

    /**
     * Create an instance of {@link CreateChemicalProductRequest }
     * 
     */
    public CreateChemicalProductRequest createCreateChemicalProductRequest() {
        return new CreateChemicalProductRequest();
    }

    /**
     * Create an instance of {@link ChemicalProductResponse }
     * 
     */
    public ChemicalProductResponse createChemicalProductResponse() {
        return new ChemicalProductResponse();
    }

    /**
     * Create an instance of {@link ChemicalProductRequest }
     * 
     */
    public ChemicalProductRequest createChemicalProductRequest() {
        return new ChemicalProductRequest();
    }

    /**
     * Create an instance of {@link GetUnitMeasureResponse }
     * 
     */
    public GetUnitMeasureResponse createGetUnitMeasureResponse() {
        return new GetUnitMeasureResponse();
    }

    /**
     * Create an instance of {@link CreateChemicalProductResponse }
     * 
     */
    public CreateChemicalProductResponse createCreateChemicalProductResponse() {
        return new CreateChemicalProductResponse();
    }

}
