//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 03:48:04 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://org/greypowerservices/webservices/productservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.greypowerservices.webservices.productservice;
