//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 12:24:26 AM COT 
//


package org.greypowerservices.webservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.greypowerservices.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ChemicalProduct_QNAME = new QName("http://webservices.greypowerservices.org", "ChemicalProduct");
    private final static QName _UnitMeasure_QNAME = new QName("http://webservices.greypowerservices.org", "UnitMeasure");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.greypowerservices.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChemicalProduct }
     * 
     */
    public ChemicalProduct createChemicalProduct() {
        return new ChemicalProduct();
    }

    /**
     * Create an instance of {@link UnitMeasure }
     * 
     */
    public UnitMeasure createUnitMeasure() {
        return new UnitMeasure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChemicalProduct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.greypowerservices.org", name = "ChemicalProduct")
    public JAXBElement<ChemicalProduct> createChemicalProduct(ChemicalProduct value) {
        return new JAXBElement<ChemicalProduct>(_ChemicalProduct_QNAME, ChemicalProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitMeasure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.greypowerservices.org", name = "UnitMeasure")
    public JAXBElement<UnitMeasure> createUnitMeasure(UnitMeasure value) {
        return new JAXBElement<UnitMeasure>(_UnitMeasure_QNAME, UnitMeasure.class, null, value);
    }

}
